.import './raw_data/AccountPermission.csv' account_permission
.import './raw_data/Customer.csv' customer
.import './raw_data/CustomerAccount.csv' customer_account
.import './raw_data/CustomerTaxrate.csv' customer_taxrate
.import './raw_data/Holding.csv' holding
.import './raw_data/HoldingHistory.csv' holding_history
.import './raw_data/HoldingSummary.csv' holding_summary
.import './raw_data/WatchItem.csv' watch_item
.import './raw_data/WatchList.csv' watch_list
.import './raw_data/Broker.csv' broker
.import './raw_data/CashTransaction.csv' cash_transaction
.import './raw_data/Charge.csv' charge
.import './raw_data/CommissionRate.csv' commission_rate
.import './raw_data/Settlement.csv' settlement
.import './raw_data/Trade.csv' trade
.import './raw_data/TradeHistory.csv' trade_history
.import './raw_data/TradeType.csv' trade_type
.import './raw_data/Company.csv' company
.import './raw_data/CompanyCompetitor.csv' company_competitor
.import './raw_data/DailyMarket.csv' daily_market
.import './raw_data/Exchange.csv' exchange
.import './raw_data/Financial.csv' financial
.import './raw_data/Industry.csv' industry
.import './raw_data/LastTrade.csv' last_trade
.import './raw_data/NewsItem.csv' news_item
.import './raw_data/NewsXRef.csv' news_xref
.import './raw_data/Sector.csv' sector
.import './raw_data/Security.csv' security
.import './raw_data/Address.csv' address
.import './raw_data/StatusType.csv' status_type
.import './raw_data/Taxrate.csv' taxrate
.import './raw_data/ZipCode.csv' zip_code
